### ISSUE TITLE
converting numeric data stored as characters to actual numeric values

### ISSUE THREAD

**Issue by vincentarelbundock** [svmiller/dragracer#5]
Thanks for the cool package!

Right now, there are a lot of columns with binary data (e.g., `missc`) that are stored as characters. Would you consider converting those to actual numeric values?

I'm happy to put together a PR if you want.

**Comment by svmiller** [comment]
Thanks for bringing that to my attention. I'll fix that in the next update.

**Comment by svmiller** [comment]
Fixed in latest version en route to CRAN. Should be good to go on Github.

**Comment by vincentarelbundock** [comment]
yessss
